#! /bin/bash
pwd_var=$(pwd)

build_and_exec()
{
	mkdir -p "$pwd_var"/build
	cd "$pwd_var"/build || exit
	cmake ../
	./main
}
build_and_exec
b_w_comp()
{
	mkdir -p "$pwd_var"/build
	cd "$pwd_var"/build || exit
}
